version: "3.1"
services:
  app:
    container_name: springapp
    image: springapp
    build: ./
    ports:
      - "8050:8050"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dadinos
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springemployeedb

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"