name: Github Action Build App Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up && Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: Build app
        run: mvn -f pom.xml --batch-mode --batch-mode --update-snapshots clean install -DskipTests
      - name: Build Images
        run: docker compose build
      - name: Created Images
        run: docker images
      - name: Run Containers
        run: docker compose up -d
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Running Containers
        run: docker ps
      - name: Stop Containers
        if: always()
        continue-on-error: true
        run: docker compose down -v